"""initial

Revision ID: 2907b9a02516
Revises: 
Create Date: 2025-11-24 01:19:12.450419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2907b9a02516'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expired_jwt', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_expired_jwt'), ['expired_jwt'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('linked_socials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('google',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linked_socials_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['linked_socials_id'], ['linked_socials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linked_socials_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['linked_socials_id'], ['linked_socials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linked_socials_id')
    )
    op.create_table('meta_liked',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('liked_name', sa.String(length=30), nullable=False),
    sa.Column('number_likes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_not_following_back',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_top_five_receiver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_top_five_sender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_liked',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('video_identifier', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['google_id'], ['google.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_subscribed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['google_id'], ['google.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_watched',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('video_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['google_id'], ['google.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_watched')
    op.drop_table('youtube_subscribed')
    op.drop_table('youtube_liked')
    op.drop_table('meta_top_five_sender')
    op.drop_table('meta_top_five_receiver')
    op.drop_table('meta_not_following_back')
    op.drop_table('meta_messages')
    op.drop_table('meta_liked')
    op.drop_table('meta')
    op.drop_table('google')
    op.drop_table('linked_socials')
    op.drop_table('users')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_expired_jwt'))

    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
